default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: rails-api_dev

# test:
#   <<: *default
#   database: rails-api_test

test:
  adapter: mysql2
  encoding: utf8
  database: github-api_test-sample_test
  pool: 20
  username: root
  password: password
  host: mysql

production:
  <<: *default
  database: rails-api_pro
